Feature branch
NiiazalyDzhumaliev/to-do-list pull request #2
Opened 2020-10-18 13:27 UTC by paulzay

### What does this PR do?
Build a todo app
### Description of tasks to be completed?
1. Build projects functionality logic
2. Build todos functionality logic
3. Display both todos and projects on the dom

2020-10-18 20:02 UTC, Forison requested changes
## Status:: Changes Required✖️
# 🙋‍♂️Dzhumaliev & Zay
#### Good job done so far, your code is well grouped in modules, here are a few issues we have to address before getting the project approved👨‍🔧.
* [ ]  Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students.([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))
* [ ] The link to the live demo in the readme is not directing to the actual page, kindly address this issue.
* [x] There should be a 'default' project.
- when the user has not created a project, all todos that are added must be stored under the default project name.
* [x] Necessary run common commands like `build`, `development` should be in `package.json` inside \`scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/))
Kindly include check my comments below

### That is it, kindly make the changes and submit a re-review👨‍🔧.

#### Happy coding 👨‍💻
Addo Forison

2020-10-18 20:02 UTC, Forison commented on src/modules/domStuff.js
> +/* eslint-disable import/prefer-default-export */
- do not make modification to you eslint configs

2020-10-18 20:02 UTC, Forison commented on src/modules/logic.js
> +/* eslint-disable import/no-mutable-exports */
do not make modification to you eslint configs

2020-10-18 20:02 UTC, Forison commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```

2020-10-19 22:30 UTC, Dandush03 approved these changes
# Status: :rocket: Project Approved :rocket: 
### Great Work! Keep It Up :muscle: 
# Happy Coding! :nerd_face: :computer:

2020-10-20 03:46 UTC, merged